import type { LangCodeISO6393 } from "@read-frog/definitions"
import {
  LANG_CODE_ISO6393_OPTIONS,
  langCodeISO6393Schema,
} from "@read-frog/definitions"
import { z } from "zod"

export type TTSVoice = string

const EDGE_TTS_VOICE_BY_ISO6393: Partial<Record<LangCodeISO6393, TTSVoice>> = {
  "eng": "en-US-AndrewMultilingualNeural",
  "cmn": "zh-CN-XiaoxiaoMultilingualNeural",
  "cmn-Hant": "zh-TW-YunJheNeural",
  "yue": "yue-CN-XiaoMinNeural",
  "spa": "es-ES-TristanMultilingualNeural",
  "rus": "ru-RU-DmitryNeural",
  "arb": "ar-SA-HamedNeural",
  "ben": "bn-BD-NabanitaNeural",
  "hin": "hi-IN-MadhurNeural",
  "por": "pt-BR-MacerioMultilingualNeural",
  "ind": "id-ID-ArdiNeural",
  "jpn": "ja-JP-MasaruMultilingualNeural",
  "fra": "fr-FR-RemyMultilingualNeural",
  "deu": "de-DE-FlorianMultilingualNeural",
  "jav": "jv-ID-DimasNeural",
  "kor": "ko-KR-HyunsuMultilingualNeural",
  "tel": "te-IN-MohanNeural",
  "vie": "vi-VN-NamMinhNeural",
  "mar": "mr-IN-ManoharNeural",
  "ita": "it-IT-AlessioMultilingualNeural",
  "tam": "ta-IN-ValluvarNeural",
  "tur": "tr-TR-AhmetNeural",
  "urd": "ur-PK-AsadNeural",
  "guj": "gu-IN-NiranjanNeural",
  "pol": "pl-PL-MarekNeural",
  "ukr": "uk-UA-OstapNeural",
  "kan": "kn-IN-GaganNeural",
  "mal": "ml-IN-MidhunNeural",
  "pes": "fa-IR-FaridNeural",
  "mya": "my-MM-ThihaNeural",
  "swh": "sw-KE-RafikiNeural",
  "sun": "su-ID-JajangNeural",
  "ron": "ro-RO-EmilNeural",
  "pan": "pa-IN-OjasNeural",
  "amh": "am-ET-AmehaNeural",
  "hau": "ha-NG-AbubakarNeural",
  "fuv": "ff-Latn-SN-SambaNeural",
  "bos": "bs-BA-GoranNeural",
  "hrv": "hr-HR-SreckoNeural",
  "nld": "nl-NL-MaartenNeural",
  "srp": "sr-RS-NicholasNeural",
  "tha": "th-TH-NiwatNeural",
  "yor": "yo-NG-AbeoNeural",
  "uzn": "uz-UZ-SardorNeural",
  "zlm": "ms-MY-OsmanNeural",
  "ibo": "ig-NG-EzinneNeural",
  "npi": "ne-NP-SagarNeural",
  "tgl": "fil-PH-AngeloNeural",
  "hun": "hu-HU-TamasNeural",
  "azj": "az-AZ-BabekNeural",
  "sin": "si-LK-SameeraNeural",
  "ell": "el-GR-NestorasNeural",
  "ces": "cs-CZ-AntoninNeural",
  "bel": "be-BY-YauheniNeural",
  "nya": "en-US-AndrewMultilingualNeural",
  "kin": "rw-RW-JeanNeural",
  "zul": "zu-ZA-ThembaNeural",
  "bul": "bg-BG-BorislavNeural",
  "swe": "sv-SE-MattiasNeural",
  "lin": "ln-CD-BaudouinNeural",
  "som": "so-SO-MuuseNeural",
  "kaz": "kk-KZ-DauletNeural",
  "heb": "he-IL-AvriNeural",
  "nob": "nb-NO-FinnNeural",
  "nno": "nn-NO-FinnNeural",
  "afr": "af-ZA-AdriNeural",
  "sqi": "sq-AL-IlirNeural",
  "asm": "as-IN-BiswajitNeural",
  "eus": "eu-ES-AnderNeural",
  "bre": "fr-FR-RemyMultilingualNeural",
  "cat": "ca-ES-EnricNeural",
  "cos": "fr-FR-RemyMultilingualNeural",
  "cym": "cy-GB-AledNeural",
  "dan": "da-DK-JeppeNeural",
  "div": "si-LK-SameeraNeural",
  "epo": "en-US-AndrewMultilingualNeural",
  "ekk": "et-EE-KertNeural",
  "fao": "fo-FO-PoulNeural",
  "fij": "en-US-AndrewMultilingualNeural",
  "fin": "fi-FI-HarriNeural",
  "fry": "nl-NL-MaartenNeural",
  "gla": "en-GB-OllieMultilingualNeural",
  "gle": "ga-IE-ColmNeural",
  "glg": "gl-ES-RoiNeural",
  "grn": "es-ES-TristanMultilingualNeural",
  "hat": "fr-FR-RemyMultilingualNeural",
  "hye": "hy-AM-HaykNeural",
  "ido": "en-US-AndrewMultilingualNeural",
  "ina": "en-US-AndrewMultilingualNeural",
  "isl": "is-IS-GunnarNeural",
  "kat": "ka-GE-GiorgiNeural",
  "khm": "km-KH-PisethNeural",
  "kir": "kk-KZ-DauletNeural",
  "lao": "lo-LA-ChanthavongNeural",
  "lat": "it-IT-AlessioMultilingualNeural",
  "lvs": "lv-LV-NilsNeural",
  "lit": "lt-LT-LeonasNeural",
  "ltz": "fr-FR-RemyMultilingualNeural",
  "mkd": "mk-MK-AleksandarNeural",
  "mlt": "mt-MT-JosephNeural",
  "mon": "mn-MN-BataaNeural",
  "mri": "en-NZ-MitchellNeural",
  "oci": "fr-FR-RemyMultilingualNeural",
  "ori": "or-IN-DineshNeural",
  "orm": "en-US-AndrewMultilingualNeural",
  "san": "hi-IN-MadhurNeural",
  "slk": "sk-SK-LukasNeural",
  "slv": "sl-SI-RokNeural",
  "smo": "en-US-AndrewMultilingualNeural",
  "sna": "en-US-AndrewMultilingualNeural",
  "snd": "sd-PK-SalmanNeural",
  "sot": "en-US-AndrewMultilingualNeural",
  "tah": "fr-FR-RemyMultilingualNeural",
  "tat": "tt-RU-AidarNeural",
  "tgk": "tg-TJ-SharifNeural",
  "tir": "am-ET-AmehaNeural",
  "ton": "en-US-AndrewMultilingualNeural",
  "tsn": "en-US-AndrewMultilingualNeural",
  "tuk": "tk-TM-AmanNeural",
  "uig": "ug-CN-KashgarNeural",
  "vol": "en-US-AndrewMultilingualNeural",
  "wol": "en-US-AndrewMultilingualNeural",
  "xho": "xh-ZA-ThembaNeural",
  "ydd": "he-IL-AvriNeural",
  "aka": "en-US-AndrewMultilingualNeural",
  "bam": "fr-FR-RemyMultilingualNeural",
  "bis": "en-US-AndrewMultilingualNeural",
  "bod": "zh-CN-XiaoxiaoMultilingualNeural",
  "che": "ru-RU-DmitryNeural",
  "chv": "ru-RU-DmitryNeural",
  "dzo": "zh-CN-XiaoxiaoMultilingualNeural",
  "ewe": "en-US-AndrewMultilingualNeural",
  "lug": "en-US-AndrewMultilingualNeural",
  "oss": "ru-RU-DmitryNeural",
  "ssw": "en-US-AndrewMultilingualNeural",
  "ven": "en-US-AndrewMultilingualNeural",
  "nde": "en-US-AndrewMultilingualNeural",
  "nbl": "en-US-AndrewMultilingualNeural",
  "cha": "en-US-AndrewMultilingualNeural",
  "mah": "en-US-AndrewMultilingualNeural",
}

export type TTSVoiceType = "Multi-talker" | "Multilingual" | "Neural HD" | "Neural HD Flash" | "Neural HD Omni" | "Standard"
export type TTSVoiceGender = "Female" | "Female, Child" | "Male" | "Neutral"

export interface TTSVoiceItem {
  voice: TTSVoice
  language: string
  type: TTSVoiceType
  gender: TTSVoiceGender
}

export interface TTSVoiceGroup {
  language: string
  items: TTSVoiceItem[]
}

// Azure Speech voices from Microsoft Learn's Text to speech voices table:
// https://learn.microsoft.com/en-us/azure/ai-services/speech-service/language-support?tabs=tts#text-to-speech-voices
// Multilingual (OpenAI) voices are intentionally excluded because the Edge consumer TTS
// endpoint used here does not include them in /cognitiveservices/voices/list and returns 400.
const EDGE_TTS_AZURE_VOICE_ITEMS: TTSVoiceItem[] = [
  { voice: "af-ZA-AdriNeural", language: "Afrikaans (South Africa)", type: "Standard", gender: "Female" },
  { voice: "af-ZA-WillemNeural", language: "Afrikaans (South Africa)", type: "Standard", gender: "Male" },
  { voice: "am-ET-MekdesNeural", language: "Amharic (Ethiopia)", type: "Standard", gender: "Female" },
  { voice: "am-ET-AmehaNeural", language: "Amharic (Ethiopia)", type: "Standard", gender: "Male" },
  { voice: "ar-AE-FatimaNeural", language: "Arabic (United Arab Emirates)", type: "Standard", gender: "Female" },
  { voice: "ar-AE-HamdanNeural", language: "Arabic (United Arab Emirates)", type: "Standard", gender: "Male" },
  { voice: "ar-BH-LailaNeural", language: "Arabic (Bahrain)", type: "Standard", gender: "Female" },
  { voice: "ar-BH-AliNeural", language: "Arabic (Bahrain)", type: "Standard", gender: "Male" },
  { voice: "ar-DZ-AminaNeural", language: "Arabic (Algeria)", type: "Standard", gender: "Female" },
  { voice: "ar-DZ-IsmaelNeural", language: "Arabic (Algeria)", type: "Standard", gender: "Male" },
  { voice: "ar-EG-SalmaNeural", language: "Arabic (Egypt)", type: "Standard", gender: "Female" },
  { voice: "ar-EG-ShakirNeural", language: "Arabic (Egypt)", type: "Standard", gender: "Male" },
  { voice: "ar-IQ-RanaNeural", language: "Arabic (Iraq)", type: "Standard", gender: "Female" },
  { voice: "ar-IQ-BasselNeural", language: "Arabic (Iraq)", type: "Standard", gender: "Male" },
  { voice: "ar-JO-SanaNeural", language: "Arabic (Jordan)", type: "Standard", gender: "Female" },
  { voice: "ar-JO-TaimNeural", language: "Arabic (Jordan)", type: "Standard", gender: "Male" },
  { voice: "ar-KW-NouraNeural", language: "Arabic (Kuwait)", type: "Standard", gender: "Female" },
  { voice: "ar-KW-FahedNeural", language: "Arabic (Kuwait)", type: "Standard", gender: "Male" },
  { voice: "ar-LB-LaylaNeural", language: "Arabic (Lebanon)", type: "Standard", gender: "Female" },
  { voice: "ar-LB-RamiNeural", language: "Arabic (Lebanon)", type: "Standard", gender: "Male" },
  { voice: "ar-LY-ImanNeural", language: "Arabic (Libya)", type: "Standard", gender: "Female" },
  { voice: "ar-LY-OmarNeural", language: "Arabic (Libya)", type: "Standard", gender: "Male" },
  { voice: "ar-MA-MounaNeural", language: "Arabic (Morocco)", type: "Standard", gender: "Female" },
  { voice: "ar-MA-JamalNeural", language: "Arabic (Morocco)", type: "Standard", gender: "Male" },
  { voice: "ar-OM-AyshaNeural", language: "Arabic (Oman)", type: "Standard", gender: "Female" },
  { voice: "ar-OM-AbdullahNeural", language: "Arabic (Oman)", type: "Standard", gender: "Male" },
  { voice: "ar-QA-AmalNeural", language: "Arabic (Qatar)", type: "Standard", gender: "Female" },
  { voice: "ar-QA-MoazNeural", language: "Arabic (Qatar)", type: "Standard", gender: "Male" },
  { voice: "ar-SA-ZariyahNeural", language: "Arabic (Saudi Arabia)", type: "Standard", gender: "Female" },
  { voice: "ar-SA-HamedNeural", language: "Arabic (Saudi Arabia)", type: "Standard", gender: "Male" },
  { voice: "ar-SY-AmanyNeural", language: "Arabic (Syria)", type: "Standard", gender: "Female" },
  { voice: "ar-SY-LaithNeural", language: "Arabic (Syria)", type: "Standard", gender: "Male" },
  { voice: "ar-TN-ReemNeural", language: "Arabic (Tunisia)", type: "Standard", gender: "Female" },
  { voice: "ar-TN-HediNeural", language: "Arabic (Tunisia)", type: "Standard", gender: "Male" },
  { voice: "ar-YE-MaryamNeural", language: "Arabic (Yemen)", type: "Standard", gender: "Female" },
  { voice: "ar-YE-SalehNeural", language: "Arabic (Yemen)", type: "Standard", gender: "Male" },
  { voice: "as-IN-YashicaNeural", language: "Assamese (India)", type: "Standard", gender: "Female" },
  { voice: "as-IN-PriyomNeural", language: "Assamese (India)", type: "Standard", gender: "Male" },
  { voice: "az-AZ-BanuNeural", language: "Azerbaijani (Latin, Azerbaijan)", type: "Standard", gender: "Female" },
  { voice: "az-AZ-BabekNeural", language: "Azerbaijani (Latin, Azerbaijan)", type: "Standard", gender: "Male" },
  { voice: "bg-BG-KalinaNeural", language: "Bulgarian (Bulgaria)", type: "Standard", gender: "Female" },
  { voice: "bg-BG-BorislavNeural", language: "Bulgarian (Bulgaria)", type: "Standard", gender: "Male" },
  { voice: "bn-BD-NabanitaNeural", language: "Bangla (Bangladesh)", type: "Standard", gender: "Female" },
  { voice: "bn-BD-PradeepNeural", language: "Bangla (Bangladesh)", type: "Standard", gender: "Male" },
  { voice: "bn-IN-TanishaaNeural", language: "Bengali (India)", type: "Standard", gender: "Female" },
  { voice: "bn-IN-BashkarNeural", language: "Bengali (India)", type: "Standard", gender: "Male" },
  { voice: "bs-BA-VesnaNeural", language: "Bosnian (Bosnia and Herzegovina)", type: "Standard", gender: "Female" },
  { voice: "bs-BA-GoranNeural", language: "Bosnian (Bosnia and Herzegovina)", type: "Standard", gender: "Male" },
  { voice: "ca-ES-JoanaNeural", language: "Catalan", type: "Standard", gender: "Female" },
  { voice: "ca-ES-EnricNeural", language: "Catalan", type: "Standard", gender: "Male" },
  { voice: "ca-ES-AlbaNeural", language: "Catalan", type: "Standard", gender: "Female" },
  { voice: "cs-CZ-VlastaNeural", language: "Czech (Czechia)", type: "Standard", gender: "Female" },
  { voice: "cs-CZ-AntoninNeural", language: "Czech (Czechia)", type: "Standard", gender: "Male" },
  { voice: "cy-GB-NiaNeural", language: "Welsh (United Kingdom)", type: "Standard", gender: "Female" },
  { voice: "cy-GB-AledNeural", language: "Welsh (United Kingdom)", type: "Standard", gender: "Male" },
  { voice: "da-DK-ChristelNeural", language: "Danish (Denmark)", type: "Standard", gender: "Female" },
  { voice: "da-DK-JeppeNeural", language: "Danish (Denmark)", type: "Standard", gender: "Male" },
  { voice: "de-AT-IngridNeural", language: "German (Austria)", type: "Standard", gender: "Female" },
  { voice: "de-AT-JonasNeural", language: "German (Austria)", type: "Standard", gender: "Male" },
  { voice: "de-CH-LeniNeural", language: "German (Switzerland)", type: "Standard", gender: "Female" },
  { voice: "de-CH-JanNeural", language: "German (Switzerland)", type: "Standard", gender: "Male" },
  { voice: "de-DE-Seraphina:DragonHDLatestNeural", language: "German (Germany)", type: "Neural HD", gender: "Female" },
  { voice: "de-DE-Florian:DragonHDLatestNeural", language: "German (Germany)", type: "Neural HD", gender: "Male" },
  { voice: "de-DE-SeraphinaMultilingualNeural", language: "German (Germany)", type: "Multilingual", gender: "Female" },
  { voice: "de-DE-FlorianMultilingualNeural", language: "German (Germany)", type: "Multilingual", gender: "Male" },
  { voice: "de-DE-KatjaNeural", language: "German (Germany)", type: "Standard", gender: "Female" },
  { voice: "de-DE-ConradNeural", language: "German (Germany)", type: "Standard", gender: "Male" },
  { voice: "de-DE-AmalaNeural", language: "German (Germany)", type: "Standard", gender: "Female" },
  { voice: "de-DE-BerndNeural", language: "German (Germany)", type: "Standard", gender: "Male" },
  { voice: "de-DE-ChristophNeural", language: "German (Germany)", type: "Standard", gender: "Male" },
  { voice: "de-DE-ElkeNeural", language: "German (Germany)", type: "Standard", gender: "Female" },
  { voice: "de-DE-GiselaNeural", language: "German (Germany)", type: "Standard", gender: "Female, Child" },
  { voice: "de-DE-KasperNeural", language: "German (Germany)", type: "Standard", gender: "Male" },
  { voice: "de-DE-KillianNeural", language: "German (Germany)", type: "Standard", gender: "Male" },
  { voice: "de-DE-KlarissaNeural", language: "German (Germany)", type: "Standard", gender: "Female" },
  { voice: "de-DE-Klaus:MAI-Voice-2", language: "German (Germany)", type: "Standard", gender: "Male" },
  { voice: "de-DE-KlausNeural", language: "German (Germany)", type: "Standard", gender: "Male" },
  { voice: "de-DE-LouisaNeural", language: "German (Germany)", type: "Standard", gender: "Female" },
  { voice: "de-DE-MajaNeural", language: "German (Germany)", type: "Standard", gender: "Female" },
  { voice: "de-DE-Mia:MAI-Voice-2", language: "German (Germany)", type: "Standard", gender: "Female" },
  { voice: "de-DE-RalfNeural", language: "German (Germany)", type: "Standard", gender: "Male" },
  { voice: "de-DE-TanjaNeural", language: "German (Germany)", type: "Standard", gender: "Female" },
  { voice: "el-GR-AthinaNeural", language: "Greek (Greece)", type: "Standard", gender: "Female" },
  { voice: "el-GR-NestorasNeural", language: "Greek (Greece)", type: "Standard", gender: "Male" },
  { voice: "en-AU-WilliamMultilingualNeural", language: "English (Australia)", type: "Multilingual", gender: "Male" },
  { voice: "en-AU-NatashaNeural", language: "English (Australia)", type: "Standard", gender: "Female" },
  { voice: "en-AU-WilliamNeural", language: "English (Australia)", type: "Standard", gender: "Male" },
  { voice: "en-AU-AnnetteNeural", language: "English (Australia)", type: "Standard", gender: "Female" },
  { voice: "en-AU-CarlyNeural", language: "English (Australia)", type: "Standard", gender: "Female" },
  { voice: "en-AU-DarrenNeural", language: "English (Australia)", type: "Standard", gender: "Male" },
  { voice: "en-AU-DuncanNeural", language: "English (Australia)", type: "Standard", gender: "Male" },
  { voice: "en-AU-ElsieNeural", language: "English (Australia)", type: "Standard", gender: "Female" },
  { voice: "en-AU-FreyaNeural", language: "English (Australia)", type: "Standard", gender: "Female" },
  { voice: "en-AU-Isla:MAI-Voice-2", language: "English (Australia)", type: "Standard", gender: "Female" },
  { voice: "en-AU-JoanneNeural", language: "English (Australia)", type: "Standard", gender: "Female" },
  { voice: "en-AU-KenNeural", language: "English (Australia)", type: "Standard", gender: "Male" },
  { voice: "en-AU-KimNeural", language: "English (Australia)", type: "Standard", gender: "Female" },
  { voice: "en-AU-NeilNeural", language: "English (Australia)", type: "Standard", gender: "Male" },
  { voice: "en-AU-TimNeural", language: "English (Australia)", type: "Standard", gender: "Male" },
  { voice: "en-AU-TinaNeural", language: "English (Australia)", type: "Standard", gender: "Female" },
  { voice: "en-CA-ClaraNeural", language: "English (Canada)", type: "Standard", gender: "Female" },
  { voice: "en-CA-LiamNeural", language: "English (Canada)", type: "Standard", gender: "Male" },
  { voice: "en-GB-Ada:DragonHDLatestNeural", language: "English (United Kingdom)", type: "Neural HD", gender: "Female" },
  { voice: "en-GB-Ollie:DragonHDLatestNeural", language: "English (United Kingdom)", type: "Neural HD", gender: "Male" },
  { voice: "en-GB-AdaMultilingualNeural", language: "English (United Kingdom)", type: "Multilingual", gender: "Female" },
  { voice: "en-GB-OllieMultilingualNeural", language: "English (United Kingdom)", type: "Multilingual", gender: "Male" },
  { voice: "en-GB-SoniaNeural", language: "English (United Kingdom)", type: "Standard", gender: "Female" },
  { voice: "en-GB-RyanNeural", language: "English (United Kingdom)", type: "Standard", gender: "Male" },
  { voice: "en-GB-LibbyNeural", language: "English (United Kingdom)", type: "Standard", gender: "Female" },
  { voice: "en-GB-AbbiNeural", language: "English (United Kingdom)", type: "Standard", gender: "Female" },
  { voice: "en-GB-AlfieNeural", language: "English (United Kingdom)", type: "Standard", gender: "Male" },
  { voice: "en-GB-BellaNeural", language: "English (United Kingdom)", type: "Standard", gender: "Female" },
  { voice: "en-GB-ElliotNeural", language: "English (United Kingdom)", type: "Standard", gender: "Male" },
  { voice: "en-GB-EthanNeural", language: "English (United Kingdom)", type: "Standard", gender: "Male" },
  { voice: "en-GB-HollieNeural", language: "English (United Kingdom)", type: "Standard", gender: "Female" },
  { voice: "en-GB-MaisieNeural", language: "English (United Kingdom)", type: "Standard", gender: "Female, Child" },
  { voice: "en-GB-NoahNeural", language: "English (United Kingdom)", type: "Standard", gender: "Male" },
  { voice: "en-GB-OliverNeural", language: "English (United Kingdom)", type: "Standard", gender: "Male" },
  { voice: "en-GB-OliviaNeural", language: "English (United Kingdom)", type: "Standard", gender: "Female" },
  { voice: "en-GB-ThomasNeural", language: "English (United Kingdom)", type: "Standard", gender: "Male" },
  { voice: "en-GB-Ryan:DragonHDLatestNeural", language: "English (United Kingdom)", type: "Standard", gender: "Male" },
  { voice: "en-GB-Sonia:DragonHDLatestNeural", language: "English (United Kingdom)", type: "Standard", gender: "Female" },
  { voice: "en-HK-YanNeural", language: "English (Hong Kong SAR)", type: "Standard", gender: "Female" },
  { voice: "en-HK-SamNeural", language: "English (Hong Kong SAR)", type: "Standard", gender: "Male" },
  { voice: "en-IE-EmilyNeural", language: "English (Ireland)", type: "Standard", gender: "Female" },
  { voice: "en-IE-ConnorNeural", language: "English (Ireland)", type: "Standard", gender: "Male" },
  { voice: "en-IN-Meera:DragonHDLatestNeural", language: "English (India)", type: "Neural HD", gender: "Female" },
  { voice: "en-IN-Aarti:DragonHDLatestNeural", language: "English (India)", type: "Neural HD", gender: "Female" },
  { voice: "en-IN-Arjun:DragonHDLatestNeural", language: "English (India)", type: "Neural HD", gender: "Male" },
  { voice: "en-IN-AartiIndicNeural", language: "English (India)", type: "Standard", gender: "Female" },
  { voice: "en-IN-ArjunIndicNeural", language: "English (India)", type: "Standard", gender: "Male" },
  { voice: "en-IN-NeerjaIndicNeural", language: "English (India)", type: "Standard", gender: "Female" },
  { voice: "en-IN-PrabhatIndicNeural", language: "English (India)", type: "Standard", gender: "Male" },
  { voice: "en-IN-AaravNeural", language: "English (India)", type: "Standard", gender: "Male" },
  { voice: "en-IN-AashiNeural", language: "English (India)", type: "Standard", gender: "Female" },
  { voice: "en-IN-AartiNeural", language: "English (India)", type: "Standard", gender: "Female" },
  { voice: "en-IN-ArjunNeural", language: "English (India)", type: "Standard", gender: "Male" },
  { voice: "en-IN-AnanyaNeural", language: "English (India)", type: "Standard", gender: "Female" },
  { voice: "en-IN-KavyaNeural", language: "English (India)", type: "Standard", gender: "Female" },
  { voice: "en-IN-KunalNeural", language: "English (India)", type: "Standard", gender: "Male" },
  { voice: "en-IN-NeerjaNeural", language: "English (India)", type: "Standard", gender: "Female" },
  { voice: "en-IN-PrabhatNeural", language: "English (India)", type: "Standard", gender: "Male" },
  { voice: "en-IN-RehaanNeural", language: "English (India)", type: "Standard", gender: "Male" },
  { voice: "en-KE-AsiliaNeural", language: "English (Kenya)", type: "Standard", gender: "Female" },
  { voice: "en-KE-ChilembaNeural", language: "English (Kenya)", type: "Standard", gender: "Male" },
  { voice: "en-NG-EzinneNeural", language: "English (Nigeria)", type: "Standard", gender: "Female" },
  { voice: "en-NG-AbeoNeural", language: "English (Nigeria)", type: "Standard", gender: "Male" },
  { voice: "en-NZ-MollyNeural", language: "English (New Zealand)", type: "Standard", gender: "Female" },
  { voice: "en-NZ-MitchellNeural", language: "English (New Zealand)", type: "Standard", gender: "Male" },
  { voice: "en-PH-RosaNeural", language: "English (Philippines)", type: "Standard", gender: "Female" },
  { voice: "en-PH-JamesNeural", language: "English (Philippines)", type: "Standard", gender: "Male" },
  { voice: "en-SG-LunaNeural", language: "English (Singapore)", type: "Standard", gender: "Female" },
  { voice: "en-SG-WayneNeural", language: "English (Singapore)", type: "Standard", gender: "Male" },
  { voice: "en-TZ-ImaniNeural", language: "English (Tanzania)", type: "Standard", gender: "Female" },
  { voice: "en-TZ-ElimuNeural", language: "English (Tanzania)", type: "Standard", gender: "Male" },
  { voice: "en-US-Ava:DragonHDLatestNeural", language: "English (United States)", type: "Neural HD", gender: "Female" },
  { voice: "en-US-Andrew:DragonHDLatestNeural", language: "English (United States)", type: "Neural HD", gender: "Male" },
  { voice: "en-US-Adam:DragonHDLatestNeural", language: "English (United States)", type: "Neural HD", gender: "Male" },
  { voice: "en-US-Alloy:DragonHDLatestNeural", language: "English (United States)", type: "Neural HD", gender: "Male" },
  { voice: "en-US-Aria:DragonHDLatestNeural", language: "English (United States)", type: "Neural HD", gender: "Female" },
  { voice: "en-US-Bree:DragonHDLatestNeural", language: "English (United States)", type: "Neural HD", gender: "Female" },
  { voice: "en-US-Brian:DragonHDLatestNeural", language: "English (United States)", type: "Neural HD", gender: "Male" },
  { voice: "en-US-Davis:DragonHDLatestNeural", language: "English (United States)", type: "Neural HD", gender: "Male" },
  { voice: "en-US-Emma:DragonHDLatestNeural", language: "English (United States)", type: "Neural HD", gender: "Female" },
  { voice: "en-US-Emma2:DragonHDLatestNeural", language: "English (United States)", type: "Neural HD", gender: "Female" },
  { voice: "en-US-Jane:DragonHDLatestNeural", language: "English (United States)", type: "Neural HD", gender: "Female" },
  { voice: "en-US-Jenny:DragonHDLatestNeural", language: "English (United States)", type: "Neural HD", gender: "Female" },
  { voice: "en-US-Nova:DragonHDLatestNeural", language: "English (United States)", type: "Neural HD", gender: "Female" },
  { voice: "en-US-Phoebe:DragonHDLatestNeural", language: "English (United States)", type: "Neural HD", gender: "Female" },
  { voice: "en-US-Serena:DragonHDLatestNeural", language: "English (United States)", type: "Neural HD", gender: "Female" },
  { voice: "en-US-Steffan:DragonHDLatestNeural", language: "English (United States)", type: "Neural HD", gender: "Male" },
  { voice: "en-US-Andrew:DragonHDOmniLatestNeural", language: "English (United States)", type: "Neural HD Omni", gender: "Male" },
  { voice: "en-US-Caleb:DragonHDOmniLatestNeural", language: "English (United States)", type: "Neural HD Omni", gender: "Male" },
  { voice: "en-US-Dana:DragonHDOmniLatestNeural", language: "English (United States)", type: "Neural HD Omni", gender: "Female" },
  { voice: "en-US-Lewis:DragonHDOmniLatestNeural", language: "English (United States)", type: "Neural HD Omni", gender: "Male" },
  { voice: "en-US-Phoebe:DragonHDOmniLatestNeural", language: "English (United States)", type: "Neural HD Omni", gender: "Female" },
  { voice: "en-US-AvaMultilingualNeural", language: "English (United States)", type: "Multilingual", gender: "Female" },
  { voice: "en-US-AndrewMultilingualNeural", language: "English (United States)", type: "Multilingual", gender: "Male" },
  { voice: "en-US-AmandaMultilingualNeural", language: "English (United States)", type: "Multilingual", gender: "Female" },
  { voice: "en-US-AdamMultilingualNeural", language: "English (United States)", type: "Multilingual", gender: "Male" },
  { voice: "en-US-EmmaMultilingualNeural", language: "English (United States)", type: "Multilingual", gender: "Female" },
  { voice: "en-US-PhoebeMultilingualNeural", language: "English (United States)", type: "Multilingual", gender: "Female" },
  { voice: "en-US-AlloyTurboMultilingualNeural", language: "English (United States)", type: "Multilingual", gender: "Male" },
  { voice: "en-US-EchoTurboMultilingualNeural", language: "English (United States)", type: "Multilingual", gender: "Male" },
  { voice: "en-US-FableTurboMultilingualNeural", language: "English (United States)", type: "Multilingual", gender: "Neutral" },
  { voice: "en-US-OnyxTurboMultilingualNeural", language: "English (United States)", type: "Multilingual", gender: "Male" },
  { voice: "en-US-NovaTurboMultilingualNeural", language: "English (United States)", type: "Multilingual", gender: "Female" },
  { voice: "en-US-ShimmerTurboMultilingualNeural", language: "English (United States)", type: "Multilingual", gender: "Female" },
  { voice: "en-US-BrianMultilingualNeural", language: "English (United States)", type: "Multilingual", gender: "Male" },
  { voice: "en-US-AvaNeural", language: "English (United States)", type: "Standard", gender: "Female" },
  { voice: "en-US-AndrewNeural", language: "English (United States)", type: "Standard", gender: "Male" },
  { voice: "en-US-EmmaNeural", language: "English (United States)", type: "Standard", gender: "Female" },
  { voice: "en-US-BrianNeural", language: "English (United States)", type: "Standard", gender: "Male" },
  { voice: "en-US-JennyNeural", language: "English (United States)", type: "Standard", gender: "Female" },
  { voice: "en-US-GuyNeural", language: "English (United States)", type: "Standard", gender: "Male" },
  { voice: "en-US-AriaNeural", language: "English (United States)", type: "Standard", gender: "Female" },
  { voice: "en-US-DavisNeural", language: "English (United States)", type: "Standard", gender: "Male" },
  { voice: "en-US-JaneNeural", language: "English (United States)", type: "Standard", gender: "Female" },
  { voice: "en-US-JasonNeural", language: "English (United States)", type: "Standard", gender: "Male" },
  { voice: "en-US-KaiNeural", language: "English (United States)", type: "Standard", gender: "Male" },
  { voice: "en-US-LunaNeural", language: "English (United States)", type: "Standard", gender: "Female" },
  { voice: "en-US-SaraNeural", language: "English (United States)", type: "Standard", gender: "Female" },
  { voice: "en-US-TonyNeural", language: "English (United States)", type: "Standard", gender: "Male" },
  { voice: "en-US-NancyNeural", language: "English (United States)", type: "Standard", gender: "Female" },
  { voice: "en-US-CoraMultilingualNeural", language: "English (United States)", type: "Multilingual", gender: "Female" },
  { voice: "en-US-ChristopherMultilingualNeural", language: "English (United States)", type: "Multilingual", gender: "Male" },
  { voice: "en-US-BrandonMultilingualNeural", language: "English (United States)", type: "Multilingual", gender: "Male" },
  { voice: "en-US-AmberNeural", language: "English (United States)", type: "Standard", gender: "Female" },
  { voice: "en-US-AnaNeural", language: "English (United States)", type: "Standard", gender: "Female, Child" },
  { voice: "en-US-AshleyNeural", language: "English (United States)", type: "Standard", gender: "Female" },
  { voice: "en-US-BrandonNeural", language: "English (United States)", type: "Standard", gender: "Male" },
  { voice: "en-US-ChristopherNeural", language: "English (United States)", type: "Standard", gender: "Male" },
  { voice: "en-US-CoraNeural", language: "English (United States)", type: "Standard", gender: "Female" },
  { voice: "en-US-DavisMultilingualNeural", language: "English (United States)", type: "Multilingual", gender: "Male" },
  { voice: "en-US-DerekMultilingualNeural", language: "English (United States)", type: "Multilingual", gender: "Male" },
  { voice: "en-US-DustinMultilingualNeural", language: "English (United States)", type: "Multilingual", gender: "Male" },
  { voice: "en-US-ElizabethNeural", language: "English (United States)", type: "Standard", gender: "Female" },
  { voice: "en-US-EricNeural", language: "English (United States)", type: "Standard", gender: "Male" },
  { voice: "en-US-EvelynMultilingualNeural", language: "English (United States)", type: "Multilingual", gender: "Female" },
  { voice: "en-US-JacobNeural", language: "English (United States)", type: "Standard", gender: "Male" },
  { voice: "en-US-JennyMultilingualNeural", language: "English (United States)", type: "Multilingual", gender: "Female" },
  { voice: "en-US-Jimmie:DragonHDFlashLatestNeural", language: "English (United States)", type: "Neural HD Flash", gender: "Male" },
  { voice: "en-US-LewisMultilingualNeural", language: "English (United States)", type: "Multilingual", gender: "Male" },
  { voice: "en-US-LolaMultilingualNeural", language: "English (United States)", type: "Multilingual", gender: "Female" },
  { voice: "en-US-MichelleNeural", language: "English (United States)", type: "Standard", gender: "Female" },
  { voice: "en-US-MonicaNeural", language: "English (United States)", type: "Standard", gender: "Female" },
  { voice: "en-US-NancyMultilingualNeural", language: "English (United States)", type: "Multilingual", gender: "Female" },
  { voice: "en-US-RogerNeural", language: "English (United States)", type: "Standard", gender: "Male" },
  { voice: "en-US-RyanMultilingualNeural", language: "English (United States)", type: "Multilingual", gender: "Male" },
  { voice: "en-US-SamuelMultilingualNeural", language: "English (United States)", type: "Multilingual", gender: "Male" },
  { voice: "en-US-SerenaMultilingualNeural", language: "English (United States)", type: "Multilingual", gender: "Female" },
  { voice: "en-US-SteffanMultilingualNeural", language: "English (United States)", type: "Multilingual", gender: "Male" },
  { voice: "en-US-SteffanNeural", language: "English (United States)", type: "Standard", gender: "Male" },
  { voice: "en-US-Tiana:DragonHDFlashLatestNeural", language: "English (United States)", type: "Neural HD Flash", gender: "Female" },
  { voice: "en-US-Tyler:DragonHDFlashLatestNeural", language: "English (United States)", type: "Neural HD Flash", gender: "Male" },
  { voice: "en-US-AIGenerate1Neural", language: "English (United States)", type: "Standard", gender: "Male" },
  { voice: "en-US-AIGenerate2Neural", language: "English (United States)", type: "Standard", gender: "Female" },
  { voice: "en-US-AshTurboMultilingualNeural", language: "English (United States)", type: "Multilingual", gender: "Male" },
  { voice: "en-US-BlueNeural", language: "English (United States)", type: "Standard", gender: "Neutral" },
  { voice: "en-US-Andrew2:DragonHDLatestNeural", language: "English (United States)", type: "Neural HD", gender: "Male" },
  { voice: "en-Multitalker:DragonHDLatestNeural", language: "English (United States)", type: "Standard", gender: "Neutral" },
  { voice: "en-US-MultiTalker-Ava-Andrew:DragonHDLatestNeural", language: "English (United States)", type: "Multi-talker", gender: "Neutral" },
  { voice: "en-US-MultiTalker-Ava-Steffan:DragonHDLatestNeural", language: "English (United States)", type: "Multi-talker", gender: "Neutral" },
  { voice: "en-US-Andrew3:DragonHDLatestNeural", language: "English (United States)", type: "Neural HD", gender: "Male" },
  { voice: "en-us-ava:DragonHDOmniLatestNeural", language: "English (United States)", type: "Neural HD Omni", gender: "Female" },
  { voice: "en-US-Ava3:DragonHDLatestNeural", language: "English (United States)", type: "Neural HD", gender: "Female" },
  { voice: "en-US-Ethan:MAI-Voice-2", language: "English (United States)", type: "Standard", gender: "Male" },
  { voice: "en-US-Grant:MAI-Voice-1", language: "English (United States)", type: "Standard", gender: "Neutral" },
  { voice: "en-US-Grant:MAI-Voice-2", language: "English (United States)", type: "Standard", gender: "Male" },
  { voice: "en-US-Harper:MAI-Voice-2", language: "English (United States)", type: "Standard", gender: "Female" },
  { voice: "en-US-Iris:MAI-Voice-1", language: "English (United States)", type: "Standard", gender: "Neutral" },
  { voice: "en-US-Iris:MAI-Voice-2", language: "English (United States)", type: "Standard", gender: "Female" },
  { voice: "en-US-Jasper:MAI-Voice-1", language: "English (United States)", type: "Standard", gender: "Neutral" },
  { voice: "en-US-Jasper:MAI-Voice-2", language: "English (United States)", type: "Standard", gender: "Male" },
  { voice: "en-US-Joy:MAI-Voice-1", language: "English (United States)", type: "Standard", gender: "Neutral" },
  { voice: "en-US-June:MAI-Voice-1", language: "English (United States)", type: "Standard", gender: "Neutral" },
  { voice: "en-US-Olivia:MAI-Voice-2", language: "English (United States)", type: "Standard", gender: "Female" },
  { voice: "en-US-Reed:MAI-Voice-1", language: "English (United States)", type: "Standard", gender: "Neutral" },
  { voice: "fr-Multitalker:DragonHDLatestNeural", language: "English (United States)", type: "Standard", gender: "Neutral" },
  { voice: "zh-Multitalker:DragonHDLatestNeural", language: "English (United States)", type: "Standard", gender: "Neutral" },
  { voice: "en-ZA-LeahNeural", language: "English (South Africa)", type: "Standard", gender: "Female" },
  { voice: "en-ZA-LukeNeural", language: "English (South Africa)", type: "Standard", gender: "Male" },
  { voice: "es-AR-ElenaNeural", language: "Spanish (Argentina)", type: "Standard", gender: "Female" },
  { voice: "es-AR-TomasNeural", language: "Spanish (Argentina)", type: "Standard", gender: "Male" },
  { voice: "es-BO-SofiaNeural", language: "Spanish (Bolivia)", type: "Standard", gender: "Female" },
  { voice: "es-BO-MarceloNeural", language: "Spanish (Bolivia)", type: "Standard", gender: "Male" },
  { voice: "es-CL-CatalinaNeural", language: "Spanish (Chile)", type: "Standard", gender: "Female" },
  { voice: "es-CL-LorenzoNeural", language: "Spanish (Chile)", type: "Standard", gender: "Male" },
  { voice: "es-CO-SalomeNeural", language: "Spanish (Colombia)", type: "Standard", gender: "Female" },
  { voice: "es-CO-GonzaloNeural", language: "Spanish (Colombia)", type: "Standard", gender: "Male" },
  { voice: "es-CR-MariaNeural", language: "Spanish (Costa Rica)", type: "Standard", gender: "Female" },
  { voice: "es-CR-JuanNeural", language: "Spanish (Costa Rica)", type: "Standard", gender: "Male" },
  { voice: "es-CU-BelkysNeural", language: "Spanish (Cuba)", type: "Standard", gender: "Female" },
  { voice: "es-CU-ManuelNeural", language: "Spanish (Cuba)", type: "Standard", gender: "Male" },
  { voice: "es-DO-RamonaNeural", language: "Spanish (Dominican Republic)", type: "Standard", gender: "Female" },
  { voice: "es-DO-EmilioNeural", language: "Spanish (Dominican Republic)", type: "Standard", gender: "Male" },
  { voice: "es-EC-AndreaNeural", language: "Spanish (Ecuador)", type: "Standard", gender: "Female" },
  { voice: "es-EC-LuisNeural", language: "Spanish (Ecuador)", type: "Standard", gender: "Male" },
  { voice: "es-ES-Ximena:DragonHDLatestNeural", language: "Spanish (Spain)", type: "Neural HD", gender: "Female" },
  { voice: "es-ES-Tristan:DragonHDLatestNeural", language: "Spanish (Spain)", type: "Neural HD", gender: "Male" },
  { voice: "es-ES-ElviraNeural", language: "Spanish (Spain)", type: "Standard", gender: "Female" },
  { voice: "es-ES-AlvaroNeural", language: "Spanish (Spain)", type: "Standard", gender: "Male" },
  { voice: "es-ES-ArabellaMultilingualNeural", language: "Spanish (Spain)", type: "Multilingual", gender: "Female" },
  { voice: "es-ES-IsidoraMultilingualNeural", language: "Spanish (Spain)", type: "Multilingual", gender: "Female" },
  { voice: "es-ES-TristanMultilingualNeural", language: "Spanish (Spain)", type: "Multilingual", gender: "Male" },
  { voice: "es-ES-XimenaMultilingualNeural", language: "Spanish (Spain)", type: "Multilingual", gender: "Female" },
  { voice: "es-ES-AbrilNeural", language: "Spanish (Spain)", type: "Standard", gender: "Female" },
  { voice: "es-ES-ArnauNeural", language: "Spanish (Spain)", type: "Standard", gender: "Male" },
  { voice: "es-ES-DarioNeural", language: "Spanish (Spain)", type: "Standard", gender: "Male" },
  { voice: "es-ES-EliasNeural", language: "Spanish (Spain)", type: "Standard", gender: "Male" },
  { voice: "es-ES-EstrellaNeural", language: "Spanish (Spain)", type: "Standard", gender: "Female" },
  { voice: "es-ES-IreneNeural", language: "Spanish (Spain)", type: "Standard", gender: "Female" },
  { voice: "es-ES-LaiaNeural", language: "Spanish (Spain)", type: "Standard", gender: "Female" },
  { voice: "es-ES-LiaNeural", language: "Spanish (Spain)", type: "Standard", gender: "Female" },
  { voice: "es-ES-NilNeural", language: "Spanish (Spain)", type: "Standard", gender: "Male" },
  { voice: "es-ES-SaulNeural", language: "Spanish (Spain)", type: "Standard", gender: "Male" },
  { voice: "es-ES-TeoNeural", language: "Spanish (Spain)", type: "Standard", gender: "Male" },
  { voice: "es-ES-TrianaNeural", language: "Spanish (Spain)", type: "Standard", gender: "Female" },
  { voice: "es-ES-VeraNeural", language: "Spanish (Spain)", type: "Standard", gender: "Female" },
  { voice: "es-ES-Marta:MAI-Voice-2", language: "Spanish (Spain)", type: "Standard", gender: "Female" },
  { voice: "es-ES-XimenaNeural", language: "Spanish (Spain)", type: "Standard", gender: "Female" },
  { voice: "es-GQ-TeresaNeural", language: "Spanish (Equatorial Guinea)", type: "Standard", gender: "Female" },
  { voice: "es-GQ-JavierNeural", language: "Spanish (Equatorial Guinea)", type: "Standard", gender: "Male" },
  { voice: "es-GT-MartaNeural", language: "Spanish (Guatemala)", type: "Standard", gender: "Female" },
  { voice: "es-GT-AndresNeural", language: "Spanish (Guatemala)", type: "Standard", gender: "Male" },
  { voice: "es-HN-KarlaNeural", language: "Spanish (Honduras)", type: "Standard", gender: "Female" },
  { voice: "es-HN-CarlosNeural", language: "Spanish (Honduras)", type: "Standard", gender: "Male" },
  { voice: "es-MX-Ximena:DragonHDLatestNeural", language: "Spanish (Mexico)", type: "Neural HD", gender: "Female" },
  { voice: "es-MX-Tristan:DragonHDLatestNeural", language: "Spanish (Mexico)", type: "Neural HD", gender: "Male" },
  { voice: "es-MX-DaliaNeural", language: "Spanish (Mexico)", type: "Standard", gender: "Female" },
  { voice: "es-MX-JorgeNeural", language: "Spanish (Mexico)", type: "Standard", gender: "Male" },
  { voice: "es-MX-DaliaMultilingualNeural", language: "Spanish (Mexico)", type: "Multilingual", gender: "Female" },
  { voice: "es-MX-JorgeMultilingualNeural", language: "Spanish (Mexico)", type: "Multilingual", gender: "Male" },
  { voice: "es-MX-Alejo:MAI-Voice-2", language: "Spanish (Mexico)", type: "Standard", gender: "Male" },
  { voice: "es-MX-BeatrizNeural", language: "Spanish (Mexico)", type: "Standard", gender: "Female" },
  { voice: "es-MX-CandelaNeural", language: "Spanish (Mexico)", type: "Standard", gender: "Female" },
  { voice: "es-MX-CarlotaNeural", language: "Spanish (Mexico)", type: "Standard", gender: "Female" },
  { voice: "es-MX-CecilioNeural", language: "Spanish (Mexico)", type: "Standard", gender: "Male" },
  { voice: "es-MX-GerardoNeural", language: "Spanish (Mexico)", type: "Standard", gender: "Male" },
  { voice: "es-MX-LarissaNeural", language: "Spanish (Mexico)", type: "Standard", gender: "Female" },
  { voice: "es-MX-LibertoNeural", language: "Spanish (Mexico)", type: "Standard", gender: "Male" },
  { voice: "es-MX-LucianoNeural", language: "Spanish (Mexico)", type: "Standard", gender: "Male" },
  { voice: "es-MX-MarinaNeural", language: "Spanish (Mexico)", type: "Standard", gender: "Female, Child" },
  { voice: "es-MX-NuriaNeural", language: "Spanish (Mexico)", type: "Standard", gender: "Female" },
  { voice: "es-MX-PelayoNeural", language: "Spanish (Mexico)", type: "Standard", gender: "Male" },
  { voice: "es-MX-RenataNeural", language: "Spanish (Mexico)", type: "Standard", gender: "Female" },
  { voice: "es-MX-Valeria:MAI-Voice-2", language: "Spanish (Mexico)", type: "Standard", gender: "Female" },
  { voice: "es-MX-YagoNeural", language: "Spanish (Mexico)", type: "Standard", gender: "Male" },
  { voice: "es-NI-YolandaNeural", language: "Spanish (Nicaragua)", type: "Standard", gender: "Female" },
  { voice: "es-NI-FedericoNeural", language: "Spanish (Nicaragua)", type: "Standard", gender: "Male" },
  { voice: "es-PA-MargaritaNeural", language: "Spanish (Panama)", type: "Standard", gender: "Female" },
  { voice: "es-PA-RobertoNeural", language: "Spanish (Panama)", type: "Standard", gender: "Male" },
  { voice: "es-PE-CamilaNeural", language: "Spanish (Peru)", type: "Standard", gender: "Female" },
  { voice: "es-PE-AlexNeural", language: "Spanish (Peru)", type: "Standard", gender: "Male" },
  { voice: "es-PR-KarinaNeural", language: "Spanish (Puerto Rico)", type: "Standard", gender: "Female" },
  { voice: "es-PR-VictorNeural", language: "Spanish (Puerto Rico)", type: "Standard", gender: "Male" },
  { voice: "es-PY-TaniaNeural", language: "Spanish (Paraguay)", type: "Standard", gender: "Female" },
  { voice: "es-PY-MarioNeural", language: "Spanish (Paraguay)", type: "Standard", gender: "Male" },
  { voice: "es-SV-LorenaNeural", language: "Spanish (El Salvador)", type: "Standard", gender: "Female" },
  { voice: "es-SV-RodrigoNeural", language: "Spanish (El Salvador)", type: "Standard", gender: "Male" },
  { voice: "es-US-PalomaNeural", language: "Spanish (United States)", type: "Standard", gender: "Female" },
  { voice: "es-US-AlonsoNeural", language: "Spanish (United States)", type: "Standard", gender: "Male" },
  { voice: "es-UY-ValentinaNeural", language: "Spanish (Uruguay)", type: "Standard", gender: "Female" },
  { voice: "es-UY-MateoNeural", language: "Spanish (Uruguay)", type: "Standard", gender: "Male" },
  { voice: "es-VE-PaolaNeural", language: "Spanish (Venezuela)", type: "Standard", gender: "Female" },
  { voice: "es-VE-SebastianNeural", language: "Spanish (Venezuela)", type: "Standard", gender: "Male" },
  { voice: "et-EE-AnuNeural", language: "Estonian (Estonia)", type: "Standard", gender: "Female" },
  { voice: "et-EE-KertNeural", language: "Estonian (Estonia)", type: "Standard", gender: "Male" },
  { voice: "eu-ES-AinhoaNeural", language: "Basque", type: "Standard", gender: "Female" },
  { voice: "eu-ES-AnderNeural", language: "Basque", type: "Standard", gender: "Male" },
  { voice: "fa-IR-DilaraNeural", language: "Persian (Iran)", type: "Standard", gender: "Female" },
  { voice: "fa-IR-FaridNeural", language: "Persian (Iran)", type: "Standard", gender: "Male" },
  { voice: "fi-FI-SelmaNeural", language: "Finnish (Finland)", type: "Standard", gender: "Female" },
  { voice: "fi-FI-HarriNeural", language: "Finnish (Finland)", type: "Standard", gender: "Male" },
  { voice: "fi-FI-NooraNeural", language: "Finnish (Finland)", type: "Standard", gender: "Female" },
  { voice: "fil-PH-BlessicaNeural", language: "Filipino (Philippines)", type: "Standard", gender: "Female" },
  { voice: "fil-PH-AngeloNeural", language: "Filipino (Philippines)", type: "Standard", gender: "Male" },
  { voice: "fr-BE-CharlineNeural", language: "French (Belgium)", type: "Standard", gender: "Female" },
  { voice: "fr-BE-GerardNeural", language: "French (Belgium)", type: "Standard", gender: "Male" },
  { voice: "fr-CA-Sylvie:DragonHDLatestNeural", language: "French (Canada)", type: "Neural HD", gender: "Female" },
  { voice: "fr-CA-Thierry:DragonHDLatestNeural", language: "French (Canada)", type: "Neural HD", gender: "Male" },
  { voice: "fr-CA-SylvieNeural", language: "French (Canada)", type: "Standard", gender: "Female" },
  { voice: "fr-CA-JeanNeural", language: "French (Canada)", type: "Standard", gender: "Male" },
  { voice: "fr-CA-AntoineNeural", language: "French (Canada)", type: "Standard", gender: "Male" },
  { voice: "fr-CA-ThierryNeural", language: "French (Canada)", type: "Standard", gender: "Male" },
  { voice: "fr-CH-ArianeNeural", language: "French (Switzerland)", type: "Standard", gender: "Female" },
  { voice: "fr-CH-FabriceNeural", language: "French (Switzerland)", type: "Standard", gender: "Male" },
  { voice: "fr-FR-Vivienne:DragonHDLatestNeural", language: "French (France)", type: "Neural HD", gender: "Female" },
  { voice: "fr-FR-Remy:DragonHDLatestNeural", language: "French (France)", type: "Neural HD", gender: "Male" },
  { voice: "fr-FR-DeniseNeural", language: "French (France)", type: "Standard", gender: "Female" },
  { voice: "fr-FR-HenriNeural", language: "French (France)", type: "Standard", gender: "Male" },
  { voice: "fr-FR-VivienneMultilingualNeural", language: "French (France)", type: "Multilingual", gender: "Female" },
  { voice: "fr-FR-RemyMultilingualNeural", language: "French (France)", type: "Multilingual", gender: "Male" },
  { voice: "fr-FR-LucienMultilingualNeural", language: "French (France)", type: "Multilingual", gender: "Male" },
  { voice: "fr-FR-AlainNeural", language: "French (France)", type: "Standard", gender: "Male" },
  { voice: "fr-FR-BrigitteNeural", language: "French (France)", type: "Standard", gender: "Female" },
  { voice: "fr-FR-CelesteNeural", language: "French (France)", type: "Standard", gender: "Female" },
  { voice: "fr-FR-ClaudeNeural", language: "French (France)", type: "Standard", gender: "Male" },
  { voice: "fr-FR-CoralieNeural", language: "French (France)", type: "Standard", gender: "Female" },
  { voice: "fr-FR-EloiseNeural", language: "French (France)", type: "Standard", gender: "Female, Child" },
  { voice: "fr-FR-JacquelineNeural", language: "French (France)", type: "Standard", gender: "Female" },
  { voice: "fr-FR-JeromeNeural", language: "French (France)", type: "Standard", gender: "Male" },
  { voice: "fr-FR-JosephineNeural", language: "French (France)", type: "Standard", gender: "Female" },
  { voice: "fr-FR-Marc:MAI-Voice-2", language: "French (France)", type: "Standard", gender: "Male" },
  { voice: "fr-FR-MauriceNeural", language: "French (France)", type: "Standard", gender: "Male" },
  { voice: "fr-FR-Soleil:MAI-Voice-2", language: "French (France)", type: "Standard", gender: "Female" },
  { voice: "fr-FR-YvesNeural", language: "French (France)", type: "Standard", gender: "Male" },
  { voice: "fr-FR-YvetteNeural", language: "French (France)", type: "Standard", gender: "Female" },
  { voice: "ga-IE-OrlaNeural", language: "Irish (Ireland)", type: "Standard", gender: "Female" },
  { voice: "ga-IE-ColmNeural", language: "Irish (Ireland)", type: "Standard", gender: "Male" },
  { voice: "gl-ES-SabelaNeural", language: "Galician", type: "Standard", gender: "Female" },
  { voice: "gl-ES-RoiNeural", language: "Galician", type: "Standard", gender: "Male" },
  { voice: "gu-IN-DhwaniNeural", language: "Gujarati (India)", type: "Standard", gender: "Female" },
  { voice: "gu-IN-NiranjanNeural", language: "Gujarati (India)", type: "Standard", gender: "Male" },
  { voice: "he-IL-HilaNeural", language: "Hebrew (Israel)", type: "Standard", gender: "Female" },
  { voice: "he-IL-AvriNeural", language: "Hebrew (Israel)", type: "Standard", gender: "Male" },
  { voice: "hi-IN-AaravNeural", language: "Hindi (India)", type: "Standard", gender: "Male" },
  { voice: "hi-IN-AnanyaNeural", language: "Hindi (India)", type: "Standard", gender: "Female" },
  { voice: "hi-IN-AartiNeural", language: "Hindi (India)", type: "Standard", gender: "Female" },
  { voice: "hi-IN-Arjun:MAI-Voice-2", language: "Hindi (India)", type: "Standard", gender: "Male" },
  { voice: "hi-IN-ArjunNeural", language: "Hindi (India)", type: "Standard", gender: "Male" },
  { voice: "hi-IN-Dhruv:MAI-Voice-2", language: "Hindi (India)", type: "Standard", gender: "Male" },
  { voice: "hi-IN-Kavya:MAI-Voice-2", language: "Hindi (India)", type: "Standard", gender: "Female" },
  { voice: "hi-IN-KavyaNeural", language: "Hindi (India)", type: "Standard", gender: "Female" },
  { voice: "hi-IN-KunalNeural", language: "Hindi (India)", type: "Standard", gender: "Male" },
  { voice: "hi-IN-RehaanNeural", language: "Hindi (India)", type: "Standard", gender: "Male" },
  { voice: "hi-IN-Priya:MAI-Voice-2", language: "Hindi (India)", type: "Standard", gender: "Female" },
  { voice: "hi-IN-SwaraNeural", language: "Hindi (India)", type: "Standard", gender: "Female" },
  { voice: "hi-IN-MadhurNeural", language: "Hindi (India)", type: "Standard", gender: "Male" },
  { voice: "hr-HR-GabrijelaNeural", language: "Croatian (Croatia)", type: "Standard", gender: "Female" },
  { voice: "hr-HR-SreckoNeural", language: "Croatian (Croatia)", type: "Standard", gender: "Male" },
  { voice: "hu-HU-Bence:MAI-Voice-2", language: "Hungarian (Hungary)", type: "Standard", gender: "Male" },
  { voice: "hu-HU-Levente:MAI-Voice-2", language: "Hungarian (Hungary)", type: "Standard", gender: "Male" },
  { voice: "hu-HU-Lilla:MAI-Voice-2", language: "Hungarian (Hungary)", type: "Standard", gender: "Female" },
  { voice: "hu-HU-NoemiNeural", language: "Hungarian (Hungary)", type: "Standard", gender: "Female" },
  { voice: "hu-HU-Réka:MAI-Voice-2", language: "Hungarian (Hungary)", type: "Standard", gender: "Female" },
  { voice: "hu-HU-TamasNeural", language: "Hungarian (Hungary)", type: "Standard", gender: "Male" },
  { voice: "hy-AM-AnahitNeural", language: "Armenian (Armenia)", type: "Standard", gender: "Female" },
  { voice: "hy-AM-HaykNeural", language: "Armenian (Armenia)", type: "Standard", gender: "Male" },
  { voice: "id-ID-GadisNeural", language: "Indonesian (Indonesia)", type: "Standard", gender: "Female" },
  { voice: "id-ID-ArdiNeural", language: "Indonesian (Indonesia)", type: "Standard", gender: "Male" },
  { voice: "is-IS-GudrunNeural", language: "Icelandic (Iceland)", type: "Standard", gender: "Female" },
  { voice: "is-IS-GunnarNeural", language: "Icelandic (Iceland)", type: "Standard", gender: "Male" },
  { voice: "it-IT-Isabella:DragonHDLatestNeural", language: "Italian (Italy)", type: "Neural HD", gender: "Female" },
  { voice: "it-IT-Alessio:DragonHDLatestNeural", language: "Italian (Italy)", type: "Neural HD", gender: "Male" },
  { voice: "it-IT-ElsaNeural", language: "Italian (Italy)", type: "Standard", gender: "Female" },
  { voice: "it-IT-IsabellaNeural", language: "Italian (Italy)", type: "Standard", gender: "Female" },
  { voice: "it-IT-DiegoNeural", language: "Italian (Italy)", type: "Standard", gender: "Male" },
  { voice: "it-IT-AlessioMultilingualNeural", language: "Italian (Italy)", type: "Multilingual", gender: "Male" },
  { voice: "it-IT-IsabellaMultilingualNeural", language: "Italian (Italy)", type: "Multilingual", gender: "Female" },
  { voice: "it-IT-GiuseppeMultilingualNeural", language: "Italian (Italy)", type: "Multilingual", gender: "Male" },
  { voice: "it-IT-MarcelloMultilingualNeural", language: "Italian (Italy)", type: "Multilingual", gender: "Male" },
  { voice: "it-IT-BenignoNeural", language: "Italian (Italy)", type: "Standard", gender: "Male" },
  { voice: "it-IT-CalimeroNeural", language: "Italian (Italy)", type: "Standard", gender: "Male" },
  { voice: "it-IT-CataldoNeural", language: "Italian (Italy)", type: "Standard", gender: "Male" },
  { voice: "it-IT-FabiolaNeural", language: "Italian (Italy)", type: "Standard", gender: "Female" },
  { voice: "it-IT-FiammaNeural", language: "Italian (Italy)", type: "Standard", gender: "Female" },
  { voice: "it-IT-GianniNeural", language: "Italian (Italy)", type: "Standard", gender: "Male" },
  { voice: "it-IT-GiuseppeNeural", language: "Italian (Italy)", type: "Standard", gender: "Male" },
  { voice: "it-IT-ImeldaNeural", language: "Italian (Italy)", type: "Standard", gender: "Female" },
  { voice: "it-IT-IrmaNeural", language: "Italian (Italy)", type: "Standard", gender: "Female" },
  { voice: "it-IT-LisandroNeural", language: "Italian (Italy)", type: "Standard", gender: "Male" },
  { voice: "it-IT-Luca:MAI-Voice-2", language: "Italian (Italy)", type: "Standard", gender: "Male" },
  { voice: "it-IT-PalmiraNeural", language: "Italian (Italy)", type: "Standard", gender: "Female" },
  { voice: "it-IT-PierinaNeural", language: "Italian (Italy)", type: "Standard", gender: "Female, Child" },
  { voice: "it-IT-RinaldoNeural", language: "Italian (Italy)", type: "Standard", gender: "Male" },
  { voice: "it-IT-Rosa:MAI-Voice-2", language: "Italian (Italy)", type: "Standard", gender: "Female" },
  { voice: "iu-Cans-CA-SiqiniqNeural", language: "Inuktitut (Syllabics, Canada)", type: "Standard", gender: "Female" },
  { voice: "iu-Cans-CA-TaqqiqNeural", language: "Inuktitut (Syllabics, Canada)", type: "Standard", gender: "Male" },
  { voice: "iu-Latn-CA-SiqiniqNeural", language: "Inuktitut (Latin, Canada)", type: "Standard", gender: "Female" },
  { voice: "iu-Latn-CA-TaqqiqNeural", language: "Inuktitut (Latin, Canada)", type: "Standard", gender: "Male" },
  { voice: "ja-JP-Nanami:DragonHDLatestNeural", language: "Japanese (Japan)", type: "Neural HD", gender: "Female" },
  { voice: "ja-JP-Masaru:DragonHDLatestNeural", language: "Japanese (Japan)", type: "Neural HD", gender: "Male" },
  { voice: "ja-JP-NanamiNeural", language: "Japanese (Japan)", type: "Standard", gender: "Female" },
  { voice: "ja-JP-KeitaNeural", language: "Japanese (Japan)", type: "Standard", gender: "Male" },
  { voice: "ja-JP-AoiNeural", language: "Japanese (Japan)", type: "Standard", gender: "Female" },
  { voice: "ja-JP-DaichiNeural", language: "Japanese (Japan)", type: "Standard", gender: "Male" },
  { voice: "ja-JP-MayuNeural", language: "Japanese (Japan)", type: "Standard", gender: "Female" },
  { voice: "ja-JP-NaokiNeural", language: "Japanese (Japan)", type: "Standard", gender: "Male" },
  { voice: "ja-JP-ShioriNeural", language: "Japanese (Japan)", type: "Standard", gender: "Female" },
  { voice: "ja-JP-MasaruMultilingualNeural", language: "Japanese (Japan)", type: "Multilingual", gender: "Male" },
  { voice: "jv-ID-SitiNeural", language: "Javanese (Latin, Indonesia)", type: "Standard", gender: "Female" },
  { voice: "jv-ID-DimasNeural", language: "Javanese (Latin, Indonesia)", type: "Standard", gender: "Male" },
  { voice: "ka-GE-EkaNeural", language: "Georgian (Georgia)", type: "Standard", gender: "Female" },
  { voice: "ka-GE-GiorgiNeural", language: "Georgian (Georgia)", type: "Standard", gender: "Male" },
  { voice: "kk-KZ-AigulNeural", language: "Kazakh (Kazakhstan)", type: "Standard", gender: "Female" },
  { voice: "kk-KZ-DauletNeural", language: "Kazakh (Kazakhstan)", type: "Standard", gender: "Male" },
  { voice: "km-KH-SreymomNeural", language: "Khmer (Cambodia)", type: "Standard", gender: "Female" },
  { voice: "km-KH-PisethNeural", language: "Khmer (Cambodia)", type: "Standard", gender: "Male" },
  { voice: "kn-IN-SapnaNeural", language: "Kannada (India)", type: "Standard", gender: "Female" },
  { voice: "kn-IN-GaganNeural", language: "Kannada (India)", type: "Standard", gender: "Male" },
  { voice: "ko-KR-SunHi:DragonHDLatestNeural", language: "Korean (Korea)", type: "Neural HD", gender: "Female" },
  { voice: "ko-KR-Hyunsu:DragonHDLatestNeural", language: "Korean (Korea)", type: "Neural HD", gender: "Male" },
  { voice: "ko-KR-SunHiNeural", language: "Korean (Korea)", type: "Standard", gender: "Female" },
  { voice: "ko-KR-InJoonNeural", language: "Korean (Korea)", type: "Standard", gender: "Male" },
  { voice: "ko-KR-HyunsuMultilingualNeural", language: "Korean (Korea)", type: "Multilingual", gender: "Male" },
  { voice: "ko-KR-BongJinNeural", language: "Korean (Korea)", type: "Standard", gender: "Male" },
  { voice: "ko-KR-GookMinNeural", language: "Korean (Korea)", type: "Standard", gender: "Male" },
  { voice: "ko-KR-Haena:MAI-Voice-2", language: "Korean (Korea)", type: "Standard", gender: "Female" },
  { voice: "ko-KR-HyunsuNeural", language: "Korean (Korea)", type: "Standard", gender: "Male" },
  { voice: "ko-KR-JiMinNeural", language: "Korean (Korea)", type: "Standard", gender: "Female" },
  { voice: "ko-KR-Junho:MAI-Voice-2", language: "Korean (Korea)", type: "Standard", gender: "Male" },
  { voice: "ko-KR-SeoHyeonNeural", language: "Korean (Korea)", type: "Standard", gender: "Female" },
  { voice: "ko-KR-SoonBokNeural", language: "Korean (Korea)", type: "Standard", gender: "Female" },
  { voice: "ko-KR-YuJinNeural", language: "Korean (Korea)", type: "Standard", gender: "Female" },
  { voice: "lo-LA-KeomanyNeural", language: "Lao (Laos)", type: "Standard", gender: "Female" },
  { voice: "lo-LA-ChanthavongNeural", language: "Lao (Laos)", type: "Standard", gender: "Male" },
  { voice: "lt-LT-OnaNeural", language: "Lithuanian (Lithuania)", type: "Standard", gender: "Female" },
  { voice: "lt-LT-LeonasNeural", language: "Lithuanian (Lithuania)", type: "Standard", gender: "Male" },
  { voice: "lv-LV-EveritaNeural", language: "Latvian (Latvia)", type: "Standard", gender: "Female" },
  { voice: "lv-LV-NilsNeural", language: "Latvian (Latvia)", type: "Standard", gender: "Male" },
  { voice: "mk-MK-MarijaNeural", language: "Macedonian (North Macedonia)", type: "Standard", gender: "Female" },
  { voice: "mk-MK-AleksandarNeural", language: "Macedonian (North Macedonia)", type: "Standard", gender: "Male" },
  { voice: "ml-IN-SobhanaNeural", language: "Malayalam (India)", type: "Standard", gender: "Female" },
  { voice: "ml-IN-MidhunNeural", language: "Malayalam (India)", type: "Standard", gender: "Male" },
  { voice: "mn-MN-YesuiNeural", language: "Mongolian (Mongolia)", type: "Standard", gender: "Female" },
  { voice: "mn-MN-BataaNeural", language: "Mongolian (Mongolia)", type: "Standard", gender: "Male" },
  { voice: "mr-IN-AarohiNeural", language: "Marathi (India)", type: "Standard", gender: "Female" },
  { voice: "mr-IN-ManoharNeural", language: "Marathi (India)", type: "Standard", gender: "Male" },
  { voice: "ms-MY-YasminNeural", language: "Malay (Malaysia)", type: "Standard", gender: "Female" },
  { voice: "ms-MY-OsmanNeural", language: "Malay (Malaysia)", type: "Standard", gender: "Male" },
  { voice: "ms-MY-Yasmin:DragonHDLatestNeural", language: "Malay (Malaysia)", type: "Standard", gender: "Female" },
  { voice: "mt-MT-GraceNeural", language: "Maltese (Malta)", type: "Standard", gender: "Female" },
  { voice: "mt-MT-JosephNeural", language: "Maltese (Malta)", type: "Standard", gender: "Male" },
  { voice: "my-MM-NilarNeural", language: "Burmese (Myanmar)", type: "Standard", gender: "Female" },
  { voice: "my-MM-ThihaNeural", language: "Burmese (Myanmar)", type: "Standard", gender: "Male" },
  { voice: "nb-NO-PernilleNeural", language: "Norwegian Bokm├Ñl (Norway)", type: "Standard", gender: "Female" },
  { voice: "nb-NO-FinnNeural", language: "Norwegian Bokm├Ñl (Norway)", type: "Standard", gender: "Male" },
  { voice: "nb-NO-IselinNeural", language: "Norwegian Bokm├Ñl (Norway)", type: "Standard", gender: "Female" },
  { voice: "ne-NP-HemkalaNeural", language: "Nepali (Nepal)", type: "Standard", gender: "Female" },
  { voice: "ne-NP-SagarNeural", language: "Nepali (Nepal)", type: "Standard", gender: "Male" },
  { voice: "nl-BE-DenaNeural", language: "Dutch (Belgium)", type: "Standard", gender: "Female" },
  { voice: "nl-BE-ArnaudNeural", language: "Dutch (Belgium)", type: "Standard", gender: "Male" },
  { voice: "nl-NL-FennaNeural", language: "Dutch (Netherlands)", type: "Standard", gender: "Female" },
  { voice: "nl-NL-Fleur:MAI-Voice-2", language: "Dutch (Netherlands)", type: "Standard", gender: "Female" },
  { voice: "nl-NL-MaartenNeural", language: "Dutch (Netherlands)", type: "Standard", gender: "Male" },
  { voice: "nl-NL-Sander:MAI-Voice-2", language: "Dutch (Netherlands)", type: "Standard", gender: "Male" },
  { voice: "nl-NL-ColetteNeural", language: "Dutch (Netherlands)", type: "Standard", gender: "Female" },
  { voice: "or-IN-SubhasiniNeural", language: "Odia (India)", type: "Standard", gender: "Female" },
  { voice: "or-IN-SukantNeural", language: "Odia (India)", type: "Standard", gender: "Male" },
  { voice: "pa-IN-OjasNeural", language: "Punjabi (India)", type: "Standard", gender: "Male" },
  { voice: "pa-IN-VaaniNeural", language: "Punjabi (India)", type: "Standard", gender: "Female" },
  { voice: "pl-PL-AgnieszkaNeural", language: "Polish (Poland)", type: "Standard", gender: "Female" },
  { voice: "pl-PL-MarekNeural", language: "Polish (Poland)", type: "Standard", gender: "Male" },
  { voice: "pl-PL-ZofiaNeural", language: "Polish (Poland)", type: "Standard", gender: "Female" },
  { voice: "ps-AF-LatifaNeural", language: "Pashto (Afghanistan)", type: "Standard", gender: "Female" },
  { voice: "ps-AF-GulNawazNeural", language: "Pashto (Afghanistan)", type: "Standard", gender: "Male" },
  { voice: "pt-BR-Thalita:DragonHDLatestNeural", language: "Portuguese (Brazil)", type: "Neural HD", gender: "Female" },
  { voice: "pt-BR-Macerio:DragonHDLatestNeural", language: "Portuguese (Brazil)", type: "Neural HD", gender: "Male" },
  { voice: "pt-BR-FranciscaNeural", language: "Portuguese (Brazil)", type: "Standard", gender: "Female" },
  { voice: "pt-BR-AntonioNeural", language: "Portuguese (Brazil)", type: "Standard", gender: "Male" },
  { voice: "pt-BR-MacerioMultilingualNeural", language: "Portuguese (Brazil)", type: "Multilingual", gender: "Male" },
  { voice: "pt-BR-ThalitaMultilingualNeural", language: "Portuguese (Brazil)", type: "Multilingual", gender: "Female" },
  { voice: "pt-BR-BrendaNeural", language: "Portuguese (Brazil)", type: "Standard", gender: "Female" },
  { voice: "pt-BR-Caio:MAI-Voice-2", language: "Portuguese (Brazil)", type: "Standard", gender: "Male" },
  { voice: "pt-BR-DonatoNeural", language: "Portuguese (Brazil)", type: "Standard", gender: "Male" },
  { voice: "pt-BR-ElzaNeural", language: "Portuguese (Brazil)", type: "Standard", gender: "Female" },
  { voice: "pt-BR-FabioNeural", language: "Portuguese (Brazil)", type: "Standard", gender: "Male" },
  { voice: "pt-BR-GiovannaNeural", language: "Portuguese (Brazil)", type: "Standard", gender: "Female" },
  { voice: "pt-BR-HumbertoNeural", language: "Portuguese (Brazil)", type: "Standard", gender: "Male" },
  { voice: "pt-BR-JulioNeural", language: "Portuguese (Brazil)", type: "Standard", gender: "Male" },
  { voice: "pt-BR-LeilaNeural", language: "Portuguese (Brazil)", type: "Standard", gender: "Female" },
  { voice: "pt-BR-LeticiaNeural", language: "Portuguese (Brazil)", type: "Standard", gender: "Female, Child" },
  { voice: "pt-BR-Luana:MAI-Voice-2", language: "Portuguese (Brazil)", type: "Standard", gender: "Female" },
  { voice: "pt-BR-ManuelaNeural", language: "Portuguese (Brazil)", type: "Standard", gender: "Female" },
  { voice: "pt-BR-NicolauNeural", language: "Portuguese (Brazil)", type: "Standard", gender: "Male" },
  { voice: "pt-BR-Pedro:MAI-Voice-2", language: "Portuguese (Brazil)", type: "Standard", gender: "Male" },
  { voice: "pt-BR-Rafael:MAI-Voice-2", language: "Portuguese (Brazil)", type: "Standard", gender: "Male" },
  { voice: "pt-BR-ThalitaNeural", language: "Portuguese (Brazil)", type: "Standard", gender: "Female" },
  { voice: "pt-BR-ValerioNeural", language: "Portuguese (Brazil)", type: "Standard", gender: "Male" },
  { voice: "pt-BR-YaraNeural", language: "Portuguese (Brazil)", type: "Standard", gender: "Female" },
  { voice: "pt-PT-RaquelNeural", language: "Portuguese (Portugal)", type: "Standard", gender: "Female" },
  { voice: "pt-PT-DuarteNeural", language: "Portuguese (Portugal)", type: "Standard", gender: "Male" },
  { voice: "pt-PT-FernandaNeural", language: "Portuguese (Portugal)", type: "Standard", gender: "Female" },
  { voice: "pt-PT-Rui:MAI-Voice-2", language: "Portuguese (Portugal)", type: "Standard", gender: "Male" },
  { voice: "ro-RO-Andrei:MAI-Voice-2", language: "Romanian (Romania)", type: "Standard", gender: "Male" },
  { voice: "ro-RO-AlinaNeural", language: "Romanian (Romania)", type: "Standard", gender: "Female" },
  { voice: "ro-RO-Elena:MAI-Voice-2", language: "Romanian (Romania)", type: "Standard", gender: "Female" },
  { voice: "ro-RO-EmilNeural", language: "Romanian (Romania)", type: "Standard", gender: "Male" },
  { voice: "ro-RO-Ioana:MAI-Voice-2", language: "Romanian (Romania)", type: "Standard", gender: "Female" },
  { voice: "ro-RO-Radu:MAI-Voice-2", language: "Romanian (Romania)", type: "Standard", gender: "Male" },
  { voice: "ru-RU-Lev:MAI-Voice-2", language: "Russian (Russia)", type: "Standard", gender: "Male" },
  { voice: "ru-RU-Masha:MAI-Voice-2", language: "Russian (Russia)", type: "Standard", gender: "Female" },
  { voice: "ru-RU-SvetlanaNeural", language: "Russian (Russia)", type: "Standard", gender: "Female" },
  { voice: "ru-RU-DmitryNeural", language: "Russian (Russia)", type: "Standard", gender: "Male" },
  { voice: "ru-RU-DariyaNeural", language: "Russian (Russia)", type: "Standard", gender: "Female" },
  { voice: "si-LK-ThiliniNeural", language: "Sinhala (Sri Lanka)", type: "Standard", gender: "Female" },
  { voice: "si-LK-SameeraNeural", language: "Sinhala (Sri Lanka)", type: "Standard", gender: "Male" },
  { voice: "sk-SK-ViktoriaNeural", language: "Slovak (Slovakia)", type: "Standard", gender: "Female" },
  { voice: "sk-SK-LukasNeural", language: "Slovak (Slovakia)", type: "Standard", gender: "Male" },
  { voice: "sl-SI-PetraNeural", language: "Slovenian (Slovenia)", type: "Standard", gender: "Female" },
  { voice: "sl-SI-RokNeural", language: "Slovenian (Slovenia)", type: "Standard", gender: "Male" },
  { voice: "so-SO-UbaxNeural", language: "Somali (Somalia)", type: "Standard", gender: "Female" },
  { voice: "so-SO-MuuseNeural", language: "Somali (Somalia)", type: "Standard", gender: "Male" },
  { voice: "sq-AL-AnilaNeural", language: "Albanian (Albania)", type: "Standard", gender: "Female" },
  { voice: "sq-AL-IlirNeural", language: "Albanian (Albania)", type: "Standard", gender: "Male" },
  { voice: "sr-Latn-RS-NicholasNeural", language: "Serbian (Latin, Serbia)", type: "Standard", gender: "Male" },
  { voice: "sr-Latn-RS-SophieNeural", language: "Serbian (Latin, Serbia)", type: "Standard", gender: "Female" },
  { voice: "sr-RS-SophieNeural", language: "Serbian (Cyrillic, Serbia)", type: "Standard", gender: "Female" },
  { voice: "sr-RS-NicholasNeural", language: "Serbian (Cyrillic, Serbia)", type: "Standard", gender: "Male" },
  { voice: "su-ID-TutiNeural", language: "Sundanese (Indonesia)", type: "Standard", gender: "Female" },
  { voice: "su-ID-JajangNeural", language: "Sundanese (Indonesia)", type: "Standard", gender: "Male" },
  { voice: "sv-SE-SofieNeural", language: "Swedish (Sweden)", type: "Standard", gender: "Female" },
  { voice: "sv-SE-MattiasNeural", language: "Swedish (Sweden)", type: "Standard", gender: "Male" },
  { voice: "sv-SE-HilleviNeural", language: "Swedish (Sweden)", type: "Standard", gender: "Female" },
  { voice: "sw-KE-ZuriNeural", language: "Kiswahili (Kenya)", type: "Standard", gender: "Female" },
  { voice: "sw-KE-RafikiNeural", language: "Kiswahili (Kenya)", type: "Standard", gender: "Male" },
  { voice: "sw-TZ-RehemaNeural", language: "Kiswahili (Tanzania)", type: "Standard", gender: "Female" },
  { voice: "sw-TZ-DaudiNeural", language: "Kiswahili (Tanzania)", type: "Standard", gender: "Male" },
  { voice: "ta-IN-PallaviNeural", language: "Tamil (India)", type: "Standard", gender: "Female" },
  { voice: "ta-IN-ValluvarNeural", language: "Tamil (India)", type: "Standard", gender: "Male" },
  { voice: "ta-LK-SaranyaNeural", language: "Tamil (Sri Lanka)", type: "Standard", gender: "Female" },
  { voice: "ta-LK-KumarNeural", language: "Tamil (Sri Lanka)", type: "Standard", gender: "Male" },
  { voice: "ta-MY-KaniNeural", language: "Tamil (Malaysia)", type: "Standard", gender: "Female" },
  { voice: "ta-MY-SuryaNeural", language: "Tamil (Malaysia)", type: "Standard", gender: "Male" },
  { voice: "ta-SG-VenbaNeural", language: "Tamil (Singapore)", type: "Standard", gender: "Female" },
  { voice: "ta-SG-AnbuNeural", language: "Tamil (Singapore)", type: "Standard", gender: "Male" },
  { voice: "te-IN-ShrutiNeural", language: "Telugu (India)", type: "Standard", gender: "Female" },
  { voice: "te-IN-MohanNeural", language: "Telugu (India)", type: "Standard", gender: "Male" },
  { voice: "th-TH-Krit:MAI-Voice-2", language: "Thai (Thailand)", type: "Standard", gender: "Male" },
  { voice: "th-TH-Nattapong:MAI-Voice-2", language: "Thai (Thailand)", type: "Standard", gender: "Male" },
  { voice: "th-TH-PremwadeeNeural", language: "Thai (Thailand)", type: "Standard", gender: "Female" },
  { voice: "th-TH-NiwatNeural", language: "Thai (Thailand)", type: "Standard", gender: "Male" },
  { voice: "th-TH-AcharaNeural", language: "Thai (Thailand)", type: "Standard", gender: "Female" },
  { voice: "tr-TR-EmelNeural", language: "Turkish (Türkiye)", type: "Standard", gender: "Female" },
  { voice: "tr-TR-AhmetNeural", language: "Turkish (Türkiye)", type: "Standard", gender: "Male" },
  { voice: "tr-TR-Aydın:MAI-Voice-2", language: "Turkish (Türkiye)", type: "Standard", gender: "Male" },
  { voice: "tr-TR-Elif:MAI-Voice-2", language: "Turkish (Türkiye)", type: "Standard", gender: "Female" },
  { voice: "uk-UA-PolinaNeural", language: "Ukrainian (Ukraine)", type: "Standard", gender: "Female" },
  { voice: "uk-UA-OstapNeural", language: "Ukrainian (Ukraine)", type: "Standard", gender: "Male" },
  { voice: "ur-IN-GulNeural", language: "Urdu (India)", type: "Standard", gender: "Female" },
  { voice: "ur-IN-SalmanNeural", language: "Urdu (India)", type: "Standard", gender: "Male" },
  { voice: "ur-PK-UzmaNeural", language: "Urdu (Pakistan)", type: "Standard", gender: "Female" },
  { voice: "ur-PK-AsadNeural", language: "Urdu (Pakistan)", type: "Standard", gender: "Male" },
  { voice: "uz-UZ-MadinaNeural", language: "Uzbek (Latin, Uzbekistan)", type: "Standard", gender: "Female" },
  { voice: "uz-UZ-SardorNeural", language: "Uzbek (Latin, Uzbekistan)", type: "Standard", gender: "Male" },
  { voice: "vi-VN-HoaiMyNeural", language: "Vietnamese (Vietnam)", type: "Standard", gender: "Female" },
  { voice: "vi-VN-NamMinhNeural", language: "Vietnamese (Vietnam)", type: "Standard", gender: "Male" },
  { voice: "wuu-CN-XiaotongNeural", language: "Chinese (Wu, Simplified)", type: "Standard", gender: "Female" },
  { voice: "wuu-CN-YunzheNeural", language: "Chinese (Wu, Simplified)", type: "Standard", gender: "Male" },
  { voice: "yue-CN-XiaoMinNeural", language: "Chinese (Cantonese, Simplified)", type: "Standard", gender: "Female" },
  { voice: "yue-CN-YunSongNeural", language: "Chinese (Cantonese, Simplified)", type: "Standard", gender: "Male" },
  { voice: "zh-CN-Xiaoxiao:DragonHDFlashLatestNeural", language: "Chinese (Mandarin, Simplified)", type: "Neural HD Flash", gender: "Female" },
  { voice: "zh-CN-Xiaoxiao2:DragonHDFlashLatestNeural", language: "Chinese (Mandarin, Simplified)", type: "Neural HD Flash", gender: "Female" },
  { voice: "zh-CN-Xiaochen:DragonHDLatestNeural", language: "Chinese (Mandarin, Simplified)", type: "Neural HD", gender: "Female" },
  { voice: "zh-CN-Yunxiao:DragonHDFlashLatestNeural", language: "Chinese (Mandarin, Simplified)", type: "Neural HD Flash", gender: "Male" },
  { voice: "zh-CN-Yunyi:DragonHDFlashLatestNeural", language: "Chinese (Mandarin, Simplified)", type: "Neural HD Flash", gender: "Male" },
  { voice: "zh-CN-Yunfan:DragonHDLatestNeural", language: "Chinese (Mandarin, Simplified)", type: "Neural HD", gender: "Male" },
  { voice: "zh-CN-Xiaoyue:DragonHDOmniLatestNeural", language: "Chinese (Mandarin, Simplified)", type: "Neural HD Omni", gender: "Female" },
  { voice: "zh-CN-Yunqi:DragonHDOmniLatestNeural", language: "Chinese (Mandarin, Simplified)", type: "Neural HD Omni", gender: "Male" },
  { voice: "zh-CN-Bo:MAI-Voice-2", language: "Chinese (Mandarin, Simplified)", type: "Standard", gender: "Male" },
  { voice: "zh-CN-Lan:MAI-Voice-2", language: "Chinese (Mandarin, Simplified)", type: "Standard", gender: "Female" },
  { voice: "zh-CN-Mei:MAI-Voice-2", language: "Chinese (Mandarin, Simplified)", type: "Standard", gender: "Female" },
  { voice: "zh-CN-Wei:MAI-Voice-2", language: "Chinese (Mandarin, Simplified)", type: "Standard", gender: "Male" },
  { voice: "zh-CN-XiaoxiaoNeural", language: "Chinese (Mandarin, Simplified)", type: "Standard", gender: "Female" },
  { voice: "zh-CN-YunxiNeural", language: "Chinese (Mandarin, Simplified)", type: "Standard", gender: "Male" },
  { voice: "zh-CN-YunjianNeural", language: "Chinese (Mandarin, Simplified)", type: "Standard", gender: "Male" },
  { voice: "zh-CN-XiaoyiNeural", language: "Chinese (Mandarin, Simplified)", type: "Standard", gender: "Female" },
  { voice: "zh-CN-YunyangNeural", language: "Chinese (Mandarin, Simplified)", type: "Standard", gender: "Male" },
  { voice: "zh-CN-XiaochenNeural", language: "Chinese (Mandarin, Simplified)", type: "Standard", gender: "Female" },
  { voice: "zh-CN-Xiaochen:DragonHDFlashLatestNeural", language: "Chinese (Mandarin, Simplified)", type: "Neural HD Flash", gender: "Female" },
  { voice: "zh-CN-XiaochenMultilingualNeural", language: "Chinese (Mandarin, Simplified)", type: "Multilingual", gender: "Female" },
  { voice: "zh-CN-Xiaohan:DragonHDFlashLatestNeural", language: "Chinese (Mandarin, Simplified)", type: "Standard", gender: "Female" },
  { voice: "zh-CN-XiaohanNeural", language: "Chinese (Mandarin, Simplified)", type: "Standard", gender: "Female" },
  { voice: "zh-CN-XiaomengNeural", language: "Chinese (Mandarin, Simplified)", type: "Standard", gender: "Female" },
  { voice: "zh-CN-XiaomoNeural", language: "Chinese (Mandarin, Simplified)", type: "Standard", gender: "Female" },
  { voice: "zh-CN-XiaoqiuNeural", language: "Chinese (Mandarin, Simplified)", type: "Standard", gender: "Female" },
  { voice: "zh-CN-XiaorouNeural", language: "Chinese (Mandarin, Simplified)", type: "Standard", gender: "Female" },
  { voice: "zh-CN-XiaoruiNeural", language: "Chinese (Mandarin, Simplified)", type: "Standard", gender: "Female" },
  { voice: "zh-CN-Xiaoshuang:DragonHDFlashLatestNeural", language: "Chinese (Mandarin, Simplified)", type: "Neural HD Flash", gender: "Female" },
  { voice: "zh-CN-XiaoshuangMultilingualNeural", language: "Chinese (Mandarin, Simplified)", type: "Multilingual", gender: "Female" },
  { voice: "zh-CN-XiaoshuangNeural", language: "Chinese (Mandarin, Simplified)", type: "Standard", gender: "Female, Child" },
  { voice: "zh-CN-XiaoxiaoDialectsNeural", language: "Chinese (Mandarin, Simplified)", type: "Standard", gender: "Female" },
  { voice: "zh-CN-XiaoxiaoMultilingualNeural", language: "Chinese (Mandarin, Simplified)", type: "Multilingual", gender: "Female" },
  { voice: "zh-CN-XiaoyanNeural", language: "Chinese (Mandarin, Simplified)", type: "Standard", gender: "Female" },
  { voice: "zh-CN-Xiaoyi:DragonHDFlashLatestNeural", language: "Chinese (Mandarin, Simplified)", type: "Neural HD Flash", gender: "Female" },
  { voice: "zh-CN-Xiaoyou:DragonHDFlashLatestNeural", language: "Chinese (Mandarin, Simplified)", type: "Neural HD Flash", gender: "Female" },
  { voice: "zh-CN-XiaoyouMultilingualNeural", language: "Chinese (Mandarin, Simplified)", type: "Multilingual", gender: "Female" },
  { voice: "zh-CN-XiaoyouNeural", language: "Chinese (Mandarin, Simplified)", type: "Standard", gender: "Female, Child" },
  { voice: "zh-CN-Xiaoyu:DragonHDFlashLatestNeural", language: "Chinese (Mandarin, Simplified)", type: "Neural HD Flash", gender: "Female" },
  { voice: "zh-CN-XiaoyuMultilingualNeural", language: "Chinese (Mandarin, Simplified)", type: "Multilingual", gender: "Female" },
  { voice: "zh-CN-XiaozhenNeural", language: "Chinese (Mandarin, Simplified)", type: "Standard", gender: "Female" },
  { voice: "zh-CN-YunfanMultilingualNeural", language: "Chinese (Mandarin, Simplified)", type: "Multilingual", gender: "Male" },
  { voice: "zh-CN-YunfengNeural", language: "Chinese (Mandarin, Simplified)", type: "Standard", gender: "Male" },
  { voice: "zh-CN-Yunhan:DragonHDFlashLatestNeural", language: "Chinese (Mandarin, Simplified)", type: "Standard", gender: "Male" },
  { voice: "zh-CN-YunhaoNeural", language: "Chinese (Mandarin, Simplified)", type: "Standard", gender: "Male" },
  { voice: "zh-CN-YunjieNeural", language: "Chinese (Mandarin, Simplified)", type: "Standard", gender: "Male" },
  { voice: "zh-CN-Yunxi:DragonHDFlashLatestNeural", language: "Chinese (Mandarin, Simplified)", type: "Standard", gender: "Male" },
  { voice: "zh-CN-Yunxia:DragonHDFlashLatestNeural", language: "Chinese (Mandarin, Simplified)", type: "Neural HD Flash", gender: "Male" },
  { voice: "zh-CN-YunxiaNeural", language: "Chinese (Mandarin, Simplified)", type: "Standard", gender: "Male" },
  { voice: "zh-CN-YunxiaoMultilingualNeural", language: "Chinese (Mandarin, Simplified)", type: "Multilingual", gender: "Male" },
  { voice: "zh-CN-Yunye:DragonHDFlashLatestNeural", language: "Chinese (Mandarin, Simplified)", type: "Neural HD Flash", gender: "Male" },
  { voice: "zh-CN-YunyeNeural", language: "Chinese (Mandarin, Simplified)", type: "Standard", gender: "Male" },
  { voice: "zh-CN-YunyiMultilingualNeural", language: "Chinese (Mandarin, Simplified)", type: "Multilingual", gender: "Male" },
  { voice: "zh-CN-YunzeNeural", language: "Chinese (Mandarin, Simplified)", type: "Standard", gender: "Male" },
  { voice: "zh-CN-guangxi-YunqiNeural", language: "Chinese (Guangxi Accent Mandarin, Simplified)", type: "Standard", gender: "Male" },
  { voice: "zh-CN-henan-YundengNeural", language: "Chinese (Zhongyuan Mandarin Henan, Simplified)", type: "Standard", gender: "Male" },
  { voice: "zh-CN-liaoning-XiaobeiNeural", language: "Chinese (Northeastern Mandarin, Simplified)", type: "Standard", gender: "Female" },
  { voice: "zh-CN-liaoning-YunbiaoNeural", language: "Chinese (Northeastern Mandarin, Simplified)", type: "Standard", gender: "Male" },
  { voice: "zh-CN-shaanxi-XiaoniNeural", language: "Chinese (Zhongyuan Mandarin Shaanxi, Simplified)", type: "Standard", gender: "Female" },
  { voice: "zh-CN-shandong-YunxiangNeural", language: "Chinese (Jilu Mandarin, Simplified)", type: "Standard", gender: "Male" },
  { voice: "zh-CN-sichuan-YunxiNeural", language: "Chinese (Southwestern Mandarin, Simplified)", type: "Standard", gender: "Male" },
  { voice: "zh-HK-HiuMaanNeural", language: "Chinese (Cantonese, Traditional)", type: "Standard", gender: "Female" },
  { voice: "zh-HK-WanLungNeural", language: "Chinese (Cantonese, Traditional)", type: "Standard", gender: "Male" },
  { voice: "zh-HK-HiuGaaiNeural", language: "Chinese (Cantonese, Traditional)", type: "Standard", gender: "Female" },
  { voice: "zh-TW-HsiaoChenNeural", language: "Chinese (Taiwanese Mandarin, Traditional)", type: "Standard", gender: "Female" },
  { voice: "zh-TW-YunJheNeural", language: "Chinese (Taiwanese Mandarin, Traditional)", type: "Standard", gender: "Male" },
  { voice: "zh-TW-HsiaoYuNeural", language: "Chinese (Taiwanese Mandarin, Traditional)", type: "Standard", gender: "Female" },
  { voice: "zu-ZA-ThandoNeural", language: "isiZulu (South Africa)", type: "Standard", gender: "Female" },
  { voice: "zu-ZA-ThembaNeural", language: "isiZulu (South Africa)", type: "Standard", gender: "Male" },
]

// Voices supported by the Edge consumer endpoint that are not present in the Azure Speech table.
const EDGE_TTS_EDGE_ONLY_VOICE_ITEMS: TTSVoiceItem[] = [
  { voice: "as-IN-BiswajitNeural", language: "Assamese (India)", type: "Standard", gender: "Neutral" },
  { voice: "be-BY-YauheniNeural", language: "Belarusian (Belarus)", type: "Standard", gender: "Neutral" },
  { voice: "ff-Latn-SN-SambaNeural", language: "Fulah (Latin, Senegal)", type: "Standard", gender: "Neutral" },
  { voice: "fo-FO-PoulNeural", language: "Faroese (Faroe Islands)", type: "Standard", gender: "Neutral" },
  { voice: "ha-NG-AbubakarNeural", language: "Hausa (Nigeria)", type: "Standard", gender: "Neutral" },
  { voice: "ig-NG-EzinneNeural", language: "Igbo (Nigeria)", type: "Standard", gender: "Neutral" },
  { voice: "ln-CD-BaudouinNeural", language: "Lingala (Congo DRC)", type: "Standard", gender: "Neutral" },
  { voice: "nn-NO-FinnNeural", language: "Norwegian Nynorsk (Norway)", type: "Standard", gender: "Neutral" },
  { voice: "or-IN-DineshNeural", language: "Odia (India)", type: "Standard", gender: "Neutral" },
  { voice: "rw-RW-JeanNeural", language: "Kinyarwanda (Rwanda)", type: "Standard", gender: "Neutral" },
  { voice: "sd-PK-SalmanNeural", language: "Sindhi (Pakistan)", type: "Standard", gender: "Neutral" },
  { voice: "tg-TJ-SharifNeural", language: "Tajik (Tajikistan)", type: "Standard", gender: "Neutral" },
  { voice: "tk-TM-AmanNeural", language: "Turkmen (Turkmenistan)", type: "Standard", gender: "Neutral" },
  { voice: "tt-RU-AidarNeural", language: "Tatar (Russia)", type: "Standard", gender: "Neutral" },
  { voice: "ug-CN-KashgarNeural", language: "Uyghur (China)", type: "Standard", gender: "Neutral" },
  { voice: "xh-ZA-ThembaNeural", language: "Xhosa (South Africa)", type: "Standard", gender: "Neutral" },
  { voice: "yo-NG-AbeoNeural", language: "Yoruba (Nigeria)", type: "Standard", gender: "Neutral" },
  { voice: "zh-CN-XiaoxuanNeural", language: "Chinese (Mandarin, Simplified)", type: "Standard", gender: "Neutral" },
]

function mergeTTSVoiceItems(items: TTSVoiceItem[]): TTSVoiceItem[] {
  const voiceItemsByName = new Map<TTSVoice, TTSVoiceItem>()
  for (const item of items) {
    voiceItemsByName.set(item.voice, item)
  }
  return [...voiceItemsByName.values()].sort((a, b) => a.voice.localeCompare(b.voice))
}

function groupTTSVoiceItemsByLanguage(items: TTSVoiceItem[]): TTSVoiceGroup[] {
  const voiceItemsByLanguage = new Map<string, TTSVoiceItem[]>()
  for (const item of items) {
    const languageItems = voiceItemsByLanguage.get(item.language)
    if (languageItems) {
      languageItems.push(item)
      continue
    }
    voiceItemsByLanguage.set(item.language, [item])
  }

  return [...voiceItemsByLanguage].map(([language, languageItems]) => ({
    language,
    items: languageItems,
  }))
}

function isTemporarilyDisabledEdgeTTSVoiceItem(item: TTSVoiceItem): boolean {
  // HD/DragonHD voices are region-dependent, while the Edge consumer token returns
  // a service-selected region that we can't control. Some DragonHD voices are
  // marked as Standard in the source table, so check both type and voice name.
  // Hide them until runtime /cognitiveservices/voices/list filtering is available.
  return item.type.includes("HD") || item.voice.includes("DragonHD")
}

export const EDGE_TTS_VOICE_ITEMS: TTSVoiceItem[] = mergeTTSVoiceItems([
  ...EDGE_TTS_AZURE_VOICE_ITEMS,
  ...EDGE_TTS_EDGE_ONLY_VOICE_ITEMS,
]).filter(item => !isTemporarilyDisabledEdgeTTSVoiceItem(item))

export const EDGE_TTS_VOICES: TTSVoice[] = EDGE_TTS_VOICE_ITEMS.map(item => item.voice)

export const EDGE_TTS_VOICE_GROUPS: TTSVoiceGroup[] = groupTTSVoiceItemsByLanguage(EDGE_TTS_VOICE_ITEMS)

const EDGE_TTS_VOICE_ITEM_BY_NAME = new Map<TTSVoice, TTSVoiceItem>(
  EDGE_TTS_VOICE_ITEMS.map(item => [item.voice, item]),
)

export function getEdgeTTSVoiceItem(voice: TTSVoice): TTSVoiceItem {
  return EDGE_TTS_VOICE_ITEM_BY_NAME.get(voice) ?? {
    voice,
    language: "Custom",
    type: "Standard",
    gender: "Neutral",
  }
}

export const EDGE_TTS_FALLBACK_VOICE: TTSVoice = "en-US-AndrewMultilingualNeural"

export function getDefaultTTSVoiceForLanguage(
  langCode: LangCodeISO6393,
  fallbackVoice: TTSVoice = EDGE_TTS_FALLBACK_VOICE,
): TTSVoice {
  return EDGE_TTS_VOICE_BY_ISO6393[langCode] ?? fallbackVoice
}

export function createDefaultTTSLanguageVoices(
  fallbackVoice: TTSVoice = EDGE_TTS_FALLBACK_VOICE,
): Record<LangCodeISO6393, TTSVoice> {
  const entries = LANG_CODE_ISO6393_OPTIONS.map((langCode) => {
    return [langCode, getDefaultTTSVoiceForLanguage(langCode, fallbackVoice)] as const
  })
  return Object.fromEntries(entries) as Record<LangCodeISO6393, TTSVoice>
}

export function isKnownEdgeTTSVoice(voice: string): boolean {
  return EDGE_TTS_VOICE_ITEM_BY_NAME.has(voice)
}

export const ttsVoiceSchema = z.string().trim().min(1)

export const MIN_TTS_RATE = -100
export const MAX_TTS_RATE = 100
export const MIN_TTS_PITCH = -100
export const MAX_TTS_PITCH = 100
export const MIN_TTS_VOLUME = -100
export const MAX_TTS_VOLUME = 100

export const ttsRateSchema = z.coerce.number().int().min(MIN_TTS_RATE).max(MAX_TTS_RATE)
export const ttsPitchSchema = z.coerce.number().int().min(MIN_TTS_PITCH).max(MAX_TTS_PITCH)
export const ttsVolumeSchema = z.coerce.number().int().min(MIN_TTS_VOLUME).max(MAX_TTS_VOLUME)

export const ttsConfigSchema = z.object({
  defaultVoice: ttsVoiceSchema,
  languageVoices: z.record(langCodeISO6393Schema, ttsVoiceSchema),
  rate: ttsRateSchema,
  pitch: ttsPitchSchema,
  volume: ttsVolumeSchema,
})

export type TTSConfig = z.infer<typeof ttsConfigSchema>
